# Generated by Django 3.1.4 on 2020-12-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cbuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cbuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cbuser',
            name='username',
        ),
    ]
